variables:
  PR_COMMENTER_IMAGE: registry.ddbuild.io/images/pr-commenter:3
  DOCKER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:24.0.4-gbi-focal
  CI_IMAGE: registry.ddbuild.io/ci/azure-log-forwarding-orchestration-ci:latest
  REPLICATED_DOCKER_REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com/lfo
stages:
  - ci-image
  - test
  - after-test
  - build
  - release
# ------------- CI IMAGE -------------
ci-build-image:
  image: $DOCKER_IMAGE
  stage: ci-image
  rules:
    - when: manual
      allow_failure: true
  tags: ["arch:amd64"]
  script:
    - docker buildx build --platform linux/amd64 --tag "$CI_IMAGE" -f "ci/build-image/Dockerfile" . --push
# ------------- CONTROL PLANE -------------
control-plane-tests:
  image: $CI_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/test.sh
  artifacts:
    paths:
      - ci/control_plane_coverage.md
control-plane-formatting:
  image: $CI_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/format.sh
control-plane-lint:
  image: $CI_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/lint.sh
type-check:
  image: $CI_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/type-check.sh
build-and-publish-tasks:
  image: $CI_IMAGE
  stage: build
  tags: ["arch:amd64"]
  dependencies:
    - forwarder-tests
    - control-plane-tests
  variables:
    KUBERNETES_POD_ANNOTATIONS_azure: cloud-iam.emissary.datadoghq.com/azure=88d13348-0530-418a-89c0-9caa32d59037
  script:
    - ci/scripts/control_plane/build_tasks.sh
    - ci/scripts/control_plane/publish.py
  only:
    refs:
      - main
build-deployer:
  image: $DOCKER_IMAGE
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  tags: ["arch:amd64"]
  script:
    - docker buildx build --platform=linux/amd64 --tag mattlogger.azurecr.io/deployer:latest -f "ci/deployer-task/Dockerfile" ./control_plane --push
# ------------- FORWARDER -------------
forwarder-tests:
  image: $CI_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/forwarder/test.sh
  artifacts:
    paths:
      - ci/forwarder_coverage.md
forwarder-build:
  image: $DOCKER_IMAGE
  stage: build
  tags: ["arch:amd64"]
  only:
    refs:
      - main
  script:
    - ci/scripts/forwarder/build_and_push.sh prerelease
forwarder-tag-build:
  image: $DOCKER_IMAGE
  stage: build
  tags: ["arch:amd64"]
  #  rules:
  #    - if: '$CI_COMMIT_TAG =~ /^v.*/'
  #      when: manual
  #    - when: never
  script:
    - ci/scripts/forwarder/build_and_push.sh v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
publish_public_tag_forwarder:
  stage: release
  #  rules:
  #    - if: '$CI_COMMIT_TAG =~ /^v.*/'
  #      when: manual
  #    - when: never
  needs:
    - forwarder-build
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: $REPLICATED_DOCKER_REGISTRY/forwarder:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    IMG_DESTINATIONS: forwarder:latest,forwarder:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
    IMG_SIGNING: "false"
# ------------- CODE COV -------------
coverage-comment:
  image: $PR_COMMENTER_IMAGE
  stage: after-test
  tags: ["arch:amd64"]
  dependencies:
    - forwarder-tests
    - control-plane-tests
  script:
    - ci/scripts/coverage-comment.sh
