variables:
  PYTHON_IMAGE: registry.ddbuild.io/images/python:3.11.6

stages:
  - test
  # - publish


run-tests:
  image: $PYTHON_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/run-tests.sh

publish-workflow:
  image: $PYTHON_IMAGE
  stage: publish
  tags: ["arch:amd64"]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/".insteadOf "https://github.com/DataDog/"
  script:
    - echo "Hello world!"
