variables:
  BAZEL_CI_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/bazel:4
  DOCKER_CI_IMAGE: registry.ddbuild.io/ci/dogweb/docker-builder:evaluation-v19967295-81b4ae8e # (2023-09-12) https://gitlab.ddbuild.io/DataDog/dogweb/-/jobs/327981116

  BASE_PIPELINE_ID: $CI_PIPELINE_ID
  PLATFORMS:
    description: |
      A list of platforms to build images for; corresponds to the
      `--platform` option of `docker buildx build`.
    value: "linux/amd64,linux/arm64"

stages:
  - build
  - test
  - publish

build-workflow:
  image: $DOCKER_CI_IMAGE
  stage: build
  tags: ["runner:main"]
  script:
    - ci/tasks/build-base-image.sh

test-workflow:
  image: $DOCKER_CI_IMAGE
  stage: test
  tags: ["runner:main"]
  script:
    - ci/tasks/run-tests.sh

publish-workflow:
  image: $BAZEL_CI_IMAGE
  stage: publish
  tags: ["runner:main"]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/".insteadOf "https://github.com/DataDog/"
  script:
    - echo "Hello world!"
