variables:
  PYTHON_IMAGE: registry.ddbuild.io/images/python:3.11.6
  PR_COMMENTER_IMAGE: registry.ddbuild.io/images/pr-commenter:3

stages:
  - test
  - afterTest

run-tests:
  image: $PYTHON_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/tasks/test.sh
  artifacts:
    paths:
      - ci/coverage.txt
type-check:
  image: $PYTHON_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/tasks/type-check.sh

coverage-comment:
  image: $PR_COMMENTER_IMAGE
  stage: afterTest
  tags: ["arch:amd64"]
  dependencies:
    - run-tests
  script:
    - ci/tasks/coverage-comment.sh

build:
  image: $PYTHON_IMAGE
  stage: afterTest
  tags: ["arch:amd64"]
  script:
    - ci/tasks/build.sh
