variables:
  BAZEL_CI_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/bazel:4
  BASE_PIPELINE_ID: $CI_PIPELINE_ID

stages:
  - build
  - test
  - publish

build-workflow:
  image: $BAZEL_CI_IMAGE
  stage: build
  tags: ["runner:main"]
  script:
    - ci/tasks/build-base-image.sh

test-workflow:
  image: $BAZEL_CI_IMAGE
  stage: test
  tags: ["runner:main"]
  script:
    - ci/tasks/run-tests.sh

publish-workflow:
  image: $BAZEL_CI_IMAGE
  stage: publish
  tags: ["runner:main"]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/".insteadOf "https://github.com/DataDog/"
  script:
    - echo "Hello world!"
