variables:
  PR_COMMENTER_IMAGE: registry.ddbuild.io/images/pr-commenter:3
  DOCKER_IMAGE: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:24.0.4-gbi-focal
  BUILD_IMAGE: registry.ddbuild.io/ci/azure-log-forwarding-offering-build:latest

stages:
  - ci-image
  - test
  - after-test

# ------------- CI IMAGE -------------
ci-build-image:
  image: $DOCKER_IMAGE
  stage: ci-image
  rules:
    - when: manual
      allow_failure: true
  tags: ["arch:amd64"]
  script:
    - docker buildx build --platform linux/amd64 --tag "$BUILD_IMAGE" -f "ci/build-image/Dockerfile" . --push

# ------------- CONTROL PLANE -------------
control-plane-tests:
  image: $BUILD_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/test.sh
  artifacts:
    paths:
      - ci/control_plane_coverage.md

type-check:
  image: $BUILD_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/type-check.sh
build:
  image: $BUILD_IMAGE
  stage: after-test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/control_plane/build.sh

# ------------- FORWARDER -------------
forwarder-tests:
  image: $BUILD_IMAGE
  stage: test
  tags: ["arch:amd64"]
  script:
    - ci/scripts/forwarder/test.sh
  artifacts:
    paths:
      - ci/forwarder_coverage.md


# ------------- CODE COV -------------
forwarder-coverage-comment:
  image: $PR_COMMENTER_IMAGE
  stage: after-test
  tags: ["arch:amd64"]
  dependencies:
    - forwarder-tests
    - control-plane-tests
  script:
    - ci/scripts/coverage-comment.sh
