[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true
warn_no_return = false
