from os import environ


TEST_CONNECTION_STRING = "TEST_CONNECTION_STRING"
TEST_EVENT_HUB_NAME = "TEST_EVENT_HUB"
TEST_EVENT_HUB_NAMESPACE = "TEST_EVENT_HUB_NAMESPACE"

environ.setdefault("AzureWebJobsStorage", TEST_CONNECTION_STRING)
environ.setdefault("EVENT_HUB_NAME", TEST_EVENT_HUB_NAME)
environ.setdefault("EVENT_HUB_NAMESPACE", TEST_EVENT_HUB_NAMESPACE)
