// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=client.go -destination=mocks/mock_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	azblob "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	gomock "go.uber.org/mock/gomock"
)

// MockAzureBlobClient is a mock of AzureBlobClient interface.
type MockAzureBlobClient struct {
	ctrl     *gomock.Controller
	recorder *MockAzureBlobClientMockRecorder
}

// MockAzureBlobClientMockRecorder is the mock recorder for MockAzureBlobClient.
type MockAzureBlobClientMockRecorder struct {
	mock *MockAzureBlobClient
}

// NewMockAzureBlobClient creates a new mock instance.
func NewMockAzureBlobClient(ctrl *gomock.Controller) *MockAzureBlobClient {
	mock := &MockAzureBlobClient{ctrl: ctrl}
	mock.recorder = &MockAzureBlobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureBlobClient) EXPECT() *MockAzureBlobClientMockRecorder {
	return m.recorder
}

// NewListBlobsFlatPager mocks base method.
func (m *MockAzureBlobClient) NewListBlobsFlatPager(containerName string, o *azblob.ListBlobsFlatOptions) *runtime.Pager[azblob.ListBlobsFlatResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListBlobsFlatPager", containerName, o)
	ret0, _ := ret[0].(*runtime.Pager[azblob.ListBlobsFlatResponse])
	return ret0
}

// NewListBlobsFlatPager indicates an expected call of NewListBlobsFlatPager.
func (mr *MockAzureBlobClientMockRecorder) NewListBlobsFlatPager(containerName, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListBlobsFlatPager", reflect.TypeOf((*MockAzureBlobClient)(nil).NewListBlobsFlatPager), containerName, o)
}

// NewListContainersPager mocks base method.
func (m *MockAzureBlobClient) NewListContainersPager(o *azblob.ListContainersOptions) *runtime.Pager[azblob.ListContainersResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListContainersPager", o)
	ret0, _ := ret[0].(*runtime.Pager[azblob.ListContainersResponse])
	return ret0
}

// NewListContainersPager indicates an expected call of NewListContainersPager.
func (mr *MockAzureBlobClientMockRecorder) NewListContainersPager(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListContainersPager", reflect.TypeOf((*MockAzureBlobClient)(nil).NewListContainersPager), o)
}
