// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=client.go -destination=mocks/mock_client.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	azblob "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
	gomock "go.uber.org/mock/gomock"
)

// MockAzureBlobClient is a mock of AzureBlobClient interface.
type MockAzureBlobClient struct {
	ctrl     *gomock.Controller
	recorder *MockAzureBlobClientMockRecorder
}

// MockAzureBlobClientMockRecorder is the mock recorder for MockAzureBlobClient.
type MockAzureBlobClientMockRecorder struct {
	mock *MockAzureBlobClient
}

// NewMockAzureBlobClient creates a new mock instance.
func NewMockAzureBlobClient(ctrl *gomock.Controller) *MockAzureBlobClient {
	mock := &MockAzureBlobClient{ctrl: ctrl}
	mock.recorder = &MockAzureBlobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureBlobClient) EXPECT() *MockAzureBlobClientMockRecorder {
	return m.recorder
}

// CreateContainer mocks base method.
func (m *MockAzureBlobClient) CreateContainer(ctx context.Context, containerName string, o *azblob.CreateContainerOptions) (azblob.CreateContainerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", ctx, containerName, o)
	ret0, _ := ret[0].(azblob.CreateContainerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockAzureBlobClientMockRecorder) CreateContainer(ctx, containerName, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockAzureBlobClient)(nil).CreateContainer), ctx, containerName, o)
}

// DownloadStream mocks base method.
func (m *MockAzureBlobClient) DownloadStream(ctx context.Context, containerName, blobName string, o *azblob.DownloadStreamOptions) (azblob.DownloadStreamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadStream", ctx, containerName, blobName, o)
	ret0, _ := ret[0].(azblob.DownloadStreamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadStream indicates an expected call of DownloadStream.
func (mr *MockAzureBlobClientMockRecorder) DownloadStream(ctx, containerName, blobName, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadStream", reflect.TypeOf((*MockAzureBlobClient)(nil).DownloadStream), ctx, containerName, blobName, o)
}

// NewListBlobsFlatPager mocks base method.
func (m *MockAzureBlobClient) NewListBlobsFlatPager(containerName string, o *azblob.ListBlobsFlatOptions) *runtime.Pager[azblob.ListBlobsFlatResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListBlobsFlatPager", containerName, o)
	ret0, _ := ret[0].(*runtime.Pager[azblob.ListBlobsFlatResponse])
	return ret0
}

// NewListBlobsFlatPager indicates an expected call of NewListBlobsFlatPager.
func (mr *MockAzureBlobClientMockRecorder) NewListBlobsFlatPager(containerName, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListBlobsFlatPager", reflect.TypeOf((*MockAzureBlobClient)(nil).NewListBlobsFlatPager), containerName, o)
}

// NewListContainersPager mocks base method.
func (m *MockAzureBlobClient) NewListContainersPager(o *azblob.ListContainersOptions) *runtime.Pager[azblob.ListContainersResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewListContainersPager", o)
	ret0, _ := ret[0].(*runtime.Pager[azblob.ListContainersResponse])
	return ret0
}

// NewListContainersPager indicates an expected call of NewListContainersPager.
func (mr *MockAzureBlobClientMockRecorder) NewListContainersPager(o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewListContainersPager", reflect.TypeOf((*MockAzureBlobClient)(nil).NewListContainersPager), o)
}

// UploadBuffer mocks base method.
func (m *MockAzureBlobClient) UploadBuffer(ctx context.Context, containerName, blobName string, buffer []byte, o *azblob.UploadBufferOptions) (azblob.UploadBufferResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadBuffer", ctx, containerName, blobName, buffer, o)
	ret0, _ := ret[0].(azblob.UploadBufferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadBuffer indicates an expected call of UploadBuffer.
func (mr *MockAzureBlobClientMockRecorder) UploadBuffer(ctx, containerName, blobName, buffer, o any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadBuffer", reflect.TypeOf((*MockAzureBlobClient)(nil).UploadBuffer), ctx, containerName, blobName, buffer, o)
}
