[project]
version = "0.0.1"
name = "azure-log-forwarding-orchestration"
requires-python = ">= 3.11"
readme = "README.md"

# common dependencies
dependencies = [
    "aiohttp==3.9.5",
    "azure-identity==1.15.0",
    "azure-storage-blob==12.20.0",
    "jsonschema==4.21.1",
]

[project.optional-dependencies]
resources_task = ["azure-mgmt-resource==23.0.1"]
diagnostic_settings_task = ["azure-mgmt-monitor==6.0.2"]
scaling_task = [
    "azure-mgmt-appcontainers==3.1.0",
    "azure-mgmt-storage==21.2.1",
    "datadog-api-client==2.26.0",
    "aiosonic==0.15.0",
    "tenacity==8.5.0",
]
deployer_task = [
    "azure-mgmt-web==7.3.0",
    "azure-mgmt-storage==21.2.1",
    # "tenacity==8.5.0",
]

dev = [
    "azure-log-forwarding-orchestration[resources_task,diagnostic_settings_task,scaling_task,deployer_task]",
    "pre-commit==3.6.2",
    "pytest==8.0.2",
    "coverage==7.4.4",
    "pycobertura==3.3.2",
    "stickytape==0.2.1",
    "mypy==1.10",
    "ruff==0.5.4",
    "types-jsonschema==4.22.0.20240610",
    "types-requests==2.32.0.20240602",
]

[build-system]
requires = ["setuptools>=70.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["tasks", "cache"]


[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
